name: Build Kivy App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk unzip zlib1g-dev libncurses5-dev libffi-dev libssl-dev
        pip install --upgrade pip setuptools
        pip install buildozer cython

    - name: Set up Android SDK
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
      run: |
        mkdir -p $ANDROID_HOME
        cd $ANDROID_HOME
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529"

    - name: Build the APK
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
      run: |
        buildozer -v android debug
